/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DesenvolvimentoIdImport } from './routes/desenvolvimento/$id'
import { Route as CronogramaIdImport } from './routes/cronograma/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DesenvolvimentoIdRoute = DesenvolvimentoIdImport.update({
  id: '/desenvolvimento/$id',
  path: '/desenvolvimento/$id',
  getParentRoute: () => rootRoute,
} as any)

const CronogramaIdRoute = CronogramaIdImport.update({
  id: '/cronograma/$id',
  path: '/cronograma/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cronograma/$id': {
      id: '/cronograma/$id'
      path: '/cronograma/$id'
      fullPath: '/cronograma/$id'
      preLoaderRoute: typeof CronogramaIdImport
      parentRoute: typeof rootRoute
    }
    '/desenvolvimento/$id': {
      id: '/desenvolvimento/$id'
      path: '/desenvolvimento/$id'
      fullPath: '/desenvolvimento/$id'
      preLoaderRoute: typeof DesenvolvimentoIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cronograma/$id': typeof CronogramaIdRoute
  '/desenvolvimento/$id': typeof DesenvolvimentoIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cronograma/$id': typeof CronogramaIdRoute
  '/desenvolvimento/$id': typeof DesenvolvimentoIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/cronograma/$id': typeof CronogramaIdRoute
  '/desenvolvimento/$id': typeof DesenvolvimentoIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cronograma/$id' | '/desenvolvimento/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cronograma/$id' | '/desenvolvimento/$id'
  id: '__root__' | '/' | '/cronograma/$id' | '/desenvolvimento/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CronogramaIdRoute: typeof CronogramaIdRoute
  DesenvolvimentoIdRoute: typeof DesenvolvimentoIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CronogramaIdRoute: CronogramaIdRoute,
  DesenvolvimentoIdRoute: DesenvolvimentoIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cronograma/$id",
        "/desenvolvimento/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/cronograma/$id": {
      "filePath": "cronograma/$id.tsx"
    },
    "/desenvolvimento/$id": {
      "filePath": "desenvolvimento/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
